---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

run:
  path: /bin/bash
  args: ["-c", "ls -alR && bash pipeline/gitgo.sh && bash pipeline/rungo.sh"]

inputs:
  - name: pipeline

